/***********************************COMBUSTIVEL***********************************/

CREATE GENERATOR GEN_COMBUSTIVEL_ID;

CREATE TABLE COMBUSTIVEL (
    ID              BIGINT NOT NULL,
    DESCRICAO       VARCHAR(255),
    VALOR_UNITARIO  DOUBLE PRECISION,
	TAXA_IMPOSTO    DOUBLE PRECISION
);

ALTER TABLE COMBUSTIVEL ADD CONSTRAINT PK_COMBUSTIVEL_01 PRIMARY KEY (ID);

CREATE OR ALTER TRIGGER COMBUSTIVEL_BI FOR COMBUSTIVEL
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_COMBUSTIVEL_ID,1);
END;

/*************************************TANQUE*************************************/

CREATE GENERATOR GEN_TANQUE_ID;

CREATE TABLE TANQUE (
    ID              BIGINT NOT NULL,
    DESCRICAO       VARCHAR(255),
    CAPACIDADE      DOUBLE PRECISION,
    ID_COMBUSTIVEL  BIGINT,
    LIMITE_BOMBAS   INTEGER
);

ALTER TABLE TANQUE ADD CONSTRAINT PK_TANQUE_01 PRIMARY KEY (ID);
ALTER TABLE TANQUE ADD CONSTRAINT FK_TANQUE_COMBUSTIBEL_01 FOREIGN KEY(ID_COMBUSTIVEL) REFERENCES COMBUSTIVEL(ID);

CREATE OR ALTER TRIGGER TANQUE_BI FOR TANQUE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_TANQUE_ID,1);
END;

/*************************************BOMBA*************************************/

CREATE GENERATOR GEN_BOMBA_ID;

CREATE TABLE BOMBA (
    ID             BIGINT NOT NULL,
    NUMERO_BOMBA   VARCHAR(10),
    DESCRICAO      VARCHAR(255),
    ID_TANQUE      BIGINT
);

ALTER TABLE BOMBA ADD CONSTRAINT PK_BOMBA_01 PRIMARY KEY (ID);
ALTER TABLE BOMBA ADD CONSTRAINT FK_BOMBA_TANQUE_01 FOREIGN KEY (ID_TANQUE) REFERENCES TANQUE (ID);

CREATE OR ALTER TRIGGER BOMBA_BI FOR BOMBA
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_BOMBA_ID,1);
END;

/*********************************ABASTECIMENTO*********************************/

CREATE GENERATOR GEN_ABASTECIMENTO_ID;

CREATE TABLE ABASTECIMENTO (
    ID              BIGINT NOT NULL,
    DATA            DATE,
    HORA            TIME,
    ID_BOMBA        BIGINT,
    QUANTIDADE      DOUBLE PRECISION,
    VALOR_UNITARIO  DOUBLE PRECISION,
    TAXA_IMPOSTO    DOUBLE PRECISION,
    VALOR_IMPOSTO   DOUBLE PRECISION,
    VALOR_TOTAL     DOUBLE PRECISION,
    ID_TANQUE       BIGINT,
    ID_COMBUSTIVEL  BIGINT
);

ALTER TABLE ABASTECIMENTO ADD CONSTRAINT PK_ABASTECIMENTO_01 PRIMARY KEY (ID);

ALTER TABLE ABASTECIMENTO ADD CONSTRAINT FK_ABASTECIMENTO_BOMBA_01 FOREIGN KEY (ID_BOMBA) REFERENCES BOMBA (ID);
ALTER TABLE ABASTECIMENTO ADD CONSTRAINT FK_ABASTECIMENTO_COMBUSTIVEL_01 FOREIGN KEY (ID_COMBUSTIVEL) REFERENCES COMBUSTIVEL (ID);
ALTER TABLE ABASTECIMENTO ADD CONSTRAINT FK_ABASTECIMENTO_TANQUE_01 FOREIGN KEY (ID_TANQUE) REFERENCES TANQUE (ID);

CREATE OR ALTER TRIGGER ABASTECIMENTO_BI FOR ABASTECIMENTO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_ABASTECIMENTO_ID,1);
END;